Landing page done
nikakhalatiani/roomy pull request #2
Opened 2024-06-30 09:36 UTC by nikakhalatiani

2024-07-01 07:47 UTC, dkurmaeva commented
Please add screenshot to PR description. It is helpful for review and if in future you need to return to the PR

2024-07-01 07:50 UTC, dkurmaeva commented
I recommend to use ESLint and Prettier

2024-07-01 08:25 UTC, dkurmaeva requested changes

2024-07-01 08:25 UTC, dkurmaeva commented on src/components/ui/button.tsx
> +      <Comp
Please avoid using shortened names

2024-07-01 19:00 UTC, nikakhalatiani commented on src/components/ui/button.tsx
> +      <Comp
This is provided element from shadcn library, I can try to change it to adapt to naming convention you suggest

2024-07-03 06:47 UTC, dkurmaeva approved these changes

2024-07-03 06:50 UTC, merged